version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_c
    hostname: redis_c
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - silver_bullet

volumes:
  redis_data:

networks:
  silver_bullet:
    name: silver_bullet